### ISSUE TITLE
You should renew you K8s admin config, because the old config was leaked.

### ISSUE THREAD

**Issue by machinly** [cool-sun/cloudApp#3]
You should renew you K8s admin config, because the old config was leaked.

https://github.com/cool-sun/cloudApp/blob/783cf5e25ba827f8bedd11f45ca10b8d2f628333/config

**Comment by cool-sun** [comment]
Thank you for reminding me, I have deleted it.

**Comment by cool-sun** [comment]
@machinly Thank you for reminding me, I have deleted it.
